DDPG:
  alfa_actor: 0.1
  alfa_critic: 0.1
  discount_factor: 0.99
  soft_target_update: 0.001
  
ADAM_param:
  actor: 0.0001
  #critic: 0.001  
  critic: 0.001
  spatial_attention : 0.01

Ornstein_Uhlenbeck:
  teta: 0.15
  sigma: 0.2  
  mu: 0

Spatial_Attention :
  spatial_att_ourdim : 30 # spatial attention output dimension
  n_sector_spatialatt : 8 # number of section used inside spatial attention
  input_spatial_size : 39 # number of elements inside each section of laser scan
  embedding_output_size : 64 #output dimension of embedding network inside spatial attention 


Training :
  nepisodes  : 500
  nsteps : 1000  
  buffer_size: 2000000
  #batch_size: 64
  batch_size : 500
  
