Reward_param:
  collision_weight : 10
  guide_weight : 0.2
  proximity_weight : 3
  collision_reward : -1
  obstacle_proximity : 1.0  
  distance_weight : 2.0

Test_Goal:
  x : 2.0 #3.6 #-2.0 #3.0 #0.67 #4.0 #2.28 #3.67 #2.95
  y : 0.0 #-7.5 #-1 #3.0 #0.0 #-0.02 #-3.19 #-0.02 #2.83  
  z : 0  
  eps_x : 0.4
  eps_y : 0.4
  eps_z : 0.0