Tiago:
  max_laser_value: 25.0 # Value considered Ok, no wall
  min_laser_value: 0.05 # Value considered there is an obstacle or crashed
  new_ranges: 2 # How many laser scan reading considered (default dimesnion of tiago io 666)
  min_range: 0.3 # Minimum meters below wich we consider we have crashed
  min_linear_velocity : 0.0
  max_linear_velocity : 0.3
  min_angular_velocity : -3.14
  max_angular_velocity : 3.14
  init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
  init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode